version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  commands:
    - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
